export const currencyMatrix = {
    'AUDUSD' : 0.8371,
    'CADUSD' : 0.8711,
    'USDCNY' : 6.1715, 
    'EURUSD' : 1.2315, 
    'GBPUSD' : 1.5683,
    'NZDUSD' : 0.7750,
    'USDJPY' : 119.95,
    'EURCZK' : 27.6028,
    'EURDKK' : 7.4405,
    'EURNOK' : 8.6651,
    'AUDAUD' : '1:1',
    'AUDCAD' : 'USD',
    'AUDCNY' : 'USD',
    'AUDCZK' : 'USD',
    'AUDDKK' : 'USD',
    'AUDEUR' : 'USD',
    'AUDGBP' : 'USD',
    'AUDJPY' : 'USD',
    'AUDNOK' : 'USD',
    'AUDNZD' : 'USD',
    'CADAUD' : 'USD',
    'CADCAD' : '1:1',
    'CADCNY' : 'USD',
    'CADCZK' : 'USD',
    'CADDKK' : 'USD',
    'CADEUR' : 'USD',
    'CADGBP' : 'USD',
    'CADJPY' : 'USD',
    'CADNOK' : 'USD',
    'CADNZD' : 'USD',
    'CNYAUD' : 'USD',
    'CNYCAD' : 'USD',
    'CNYCNY' : '1:1',
    'CNYCZK' : 'USD',
    'CNYDKK' : 'USD',
    'CNYEUR' : 'USD',
    'CNYGBP' : 'USD',
    'CNYJPY' : 'USD',
    'CNYNOK' : 'USD',
    'CNYNZD' : 'USD',
    'CNYUSD' : 'INV',
    'CZKAUD' : 'USD',
    'CZKCAD' : 'USD',
    'CZKCNY' : 'USD',
    'CZKCZK' : '1:1',
    'CZKDKK' : 'EUR',
    'CZKEUR' : 'INV',
    'CZKGBP' : 'USD',
    'CZKJPY' : 'USD',
    'CZKNOK' : 'EUR',
    'CZKNZD' : 'USD',
    'CZKUSD' : 'EUR',
    'DKKAUD' : 'USD',
    'DKKCAD' : 'USD',
    'DKKCNY' : 'USD',
    'DKKCZK' : 'EUR',
    'DKKDKK' : '1:1',
    'DKKEUR' : 'INV',
    'DKKGBP' : 'USD',
    'DKKJPY' : 'USD',
    'DKKNOK' : 'EUR',
    'DKKNZD' : 'USD',
    'DKKUSD' : 'EUR',
    'EURAUD' : 'USD',
    'EURCAD' : 'USD',
    'EURCNY' : 'USD',
    'EUREUR' : '1:1',
    'EURGBP' : 'USD',
    'EURJPY' : 'USD',
    'EURNZD' : 'USD',
    'GBPAUD' : 'USD',
    'GBPCAD' : 'USD',
    'GBPCNY' : 'USD',
    'GBPCZK' : 'USD',
    'GBPDKK' : 'USD',
    'GBPEUR' : 'USD',
    'GBPGBP' : '1:1',
    'GBPJPY' : 'USD',
    'GBPNOK' : 'USD',
    'GBPNZD' : 'USD',
    'JPYAUD' : 'USD',
    'JPYCAD' : 'USD',
    'JPYCNY' : 'USD',
    'JPYCZK' : 'USD',
    'JPYDKK' : 'USD',
    'JPYEUR' : 'USD',
    'JPYGBP' : 'USD',
    'JPYJPY' : '1:1',
    'JPYNOK' : 'USD',
    'JPYNZD' : 'USD',
    'JPYUSD' : 'INV',
    'NOKAUD' : 'USD',
    'NOKCAD' : 'USD',
    'NOKCNY' : 'USD',
    'NOKCZK' : 'EUR',
    'NOKDKK' : 'EUR',
    'NOKEUR' : 'INV',
    'NOKGBP' : 'USD',
    'NOKJPY' : 'USD',
    'NOKNOK' : '1:1',
    'NOKNZD' : 'USD',
    'NOKUSD' : 'EUR',
    'NZDAUD' : 'USD',
    'NZDCAD' : 'USD',
    'NZDCNY' : 'USD',
    'NZDCZK' : 'USD',
    'NZDDKK' : 'USD',
    'NZDEUR' : 'USD',
    'NZDGBP' : 'USD',
    'NZDJPY' : 'USD',
    'NZDNOK' : 'USD',
    'NZDNZD' : '1:1',
    'USDAUD' : 'INV',
    'USDCAD' : 'INV',
    'USDCZK' : 'EUR',
    'USDDKK' : 'EUR',
    'USDEUR' : 'INV',
    'USDGBP' : 'INV',
    'USDNOK' : 'EUR',
    'USDNZD' : 'INV',
    'USDUSD' : '1:1'
};
export const amountValidator = new RegExp('^[0-9.]+$');

export const isNumeric = (num) => /^-{0,1}\d*\.{0,1}\d+$/.test(num);

export const handleCalculation = (fromCurrency, toCurrency, amount) => {
  const currencyRateHelper = (fromCurrency, toCurrency) => {
    let rate = currencyMatrix[fromCurrency + toCurrency];
    if(rate === 'INV') {
      let inverseRate = 1 / currencyMatrix[toCurrency + fromCurrency];
      amount = Number(amount) * inverseRate;
      return;
    } else if(rate === '1:1') {
      return;
    } else if(isNumeric(rate)) {
      amount = Number(amount) * rate;
      return;
    }
    currencyRateHelper(fromCurrency, rate);
    currencyRateHelper(rate, toCurrency);
  }
  currencyRateHelper(fromCurrency, toCurrency);
  return amount;
}